services:
    phpbb.boardannouncements.listener:
        class: phpbb\boardannouncements\event\listener
        arguments:
            - @config
            - @template
            - @user
            - @service_container
        tags:
            - { name: event.listener }
